### ISSUE TITLE
Add ability to adjust size of Title text

### ISSUE THREAD

**Issue by aashreys** [Julien-Marcou/Unicode-Emoji-Picker#1]
Hi, I'd like to adjust the size of the title text of the emoji picker component but there is currently no css variable to do that. Could you please add a way to adjust the title text size? 

Thank you!

**Comment by Julien-Marcou** [comment]
Hi 🙂

This feature has been implemented in the [v1.4.0](https://github.com/Julien-Marcou/Unicode-Emoji-Picker/releases/tag/v1.4.0)
